// Code generated by gen.go. DO NOT EDIT.

//go:build !ebitenexternaldll
// +build !ebitenexternaldll

package glfw

const glfwDLLHash = "09dc0356bd5e95cb91fd67d785fa2483ccce0e093319d00be1454dd1ffdffe2d"
