// Code generated by gen.go. DO NOT EDIT.

//go:build !ebitenexternaldll
// +build !ebitenexternaldll

package glfw

const glfwDLLHash = "956cb32b0b235fccf9c1fb50bb22d729281a3736675317a9b5d7a6d75eb02cc1"
